### ISSUE TITLE
Update https://chainid.network/chains.json after v1.2 activated on mainnet

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/babel-api#6]
Shall use

http://babel-api.testnet.iotex.io
http://babel-api.mainnet.iotex.io

**Comment by maswalker** [comment]
updated in README
The service would be deployed as below,

    Mainnet
        Host: https://babel-api.mainnet.iotex.io
        Chain ID: 4689
    Testnet
        Host: https://babel-api.testnet.iotex.io
        Chain ID: 4690
