### ISSUE TITLE
data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.1.2)

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/babel-api#7]
```
pragma solidity ^0.5.17;

contract TestIOTX{

    function getBalance() public view returns(uint256){
        return address(this).balance;
    }
}
```

Using remix to invoke getBalance(), one gets such an error
`
Failed to decode output: Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.1.2)
`

![Screen Shot 2021-05-27 at 12 10 12 PM](https://user-images.githubusercontent.com/989846/119883521-7e8e2d80-bee4-11eb-81f1-57870f62ec28.png)

**Comment by maswalker** [comment]
Please set EVM VERSION=petersburg in remix, refer to
https://ethereum.stackexchange.com/questions/78597/solidity-0-6-0-addressthis-balance-throws-error-invalid-opcode
